apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-collector-logs-writer 
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: logging-collector-logs-writer                 
subjects:                                          
  - kind: ServiceAccount                           
    name: collector              
    namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collect-application-logs
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: collect-application-logs                 
subjects:                                          
  - kind: ServiceAccount                           
    name: collector              
    namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collect-audit-logs
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: collect-audit-logs                 
subjects:                                          
  - kind: ServiceAccount                           
    name: collector              
    namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collect-infrastructure-logs
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: collect-infrastructure-logs                 
subjects:                                          
  - kind: ServiceAccount                           
    name: collector              
    namespace: openshift-logging
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cluster-logging-write-application-logs
# rules:                                              
#   - apiGroups:                                      
#       - loki.grafana.com                            
#     resources:                                      
#       - application                                 
#     resourceNames:                                  
#       - logs                                        
#     verbs:                                          
#       - create                                      
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cluster-logging-write-infrastructure-logs
# rules:                                              
#   - apiGroups:                                      
#       - loki.grafana.com                            
#     resources:                                      
#       - infrastructure                              
#     resourceNames:                                  
#       - logs                                        
#     verbs:                                          
#       - create
# --- 
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cluster-logging-write-audit-logs
# rules:                                              
#   - apiGroups:                                      
#       - loki.grafana.com                            
#     resources:                                      
#       - audit                                       
#     resourceNames:                                  
#       - logs                                        
#     verbs:                                          
#       - create                  
# --- 
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: clusterlogforwarder-editor-role
# rules:                                              
#   - apiGroups:                                      
#       - observability.openshift.io                  
#     resources:                                      
#       - clusterlogforwarders                        
#     verbs:                                          
#       - create                                      
#       - delete                                      
#       - get                                         
#       - list                                        
#       - patch                                       
#       - update                                      
#       - watch                                       