FROM registry.access.redhat.com/ubi9-minimal:latest
COPY nexus-cli /opt/nexus-cli/nexus-cli
RUN mkdir -p /opt/rox && \ 
    curl -L -o /opt/rox/roxctl https://mirror.openshift.com/pub/rhacs/assets/latest/bin/Linux/roxctl && \ 
    chmod -R 755 /opt/rox/roxctl && \ 
    chown -R 1001:0 /opt/rox/roxctl && \ 
    chmod -R 755 /opt/nexus-cli/nexus-cli && \
    chown -R 1001:0 /opt/nexus-cli
ENV PATH=/opt/nexus-cli:/opt/rox:$PATH
USER 1001
