{
 "title": "Quarkus App",
 "description": "Quarkus Micrometer Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error Rate [5m]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",outcome=\"SUCCESS\"}[1m]))/sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[1m]))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request/sec",
   "type": "stat",
   "description": "Current TPS",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(quantile_over_time(0.95, http_server_requests_seconds_max{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "description": "Average max response time",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " avg(http_server_requests_seconds_max{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"})/1048576"
    }
   ]
  }
 ]
}