{
 "title": "Backend App",
 "description": "Backend Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_concurrentBackend_current"
    }
   ]
  },
  {
   "title": "Total Concurrent Requests",
   "type": "stat",
   "description": "Average 1 minutes",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(application_com_example_quarkus_BackendResource_countBackend_total[1m]))"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(base_memory_usedHeap_bytes[5m])"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_timeBackend_seconds{quantile=\"0.99\"}"
    }
   ]
  }
 ]
}