apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: ACCESS_KEY_ID
  access_key_secret: SECRET_ACCESS_KEY
  bucketnames: S3_BUCKET
  endpoint: ENDPOINT
  region: REGION
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  rules:
    enabled: true # Enable Alert
    selector:
      matchLabels:
        openshift.io/cluster-monitoring: "true" # Only consider rules matching these labels
    namespaceSelector:
      matchLabels:
        openshift.io/cluster-monitoring: "true" # Only consider rules in namespaces matching these labels
  size: 1x.pico # 1x.extra-small #1x.small
  storage:
    schemas:
    - effectiveDate: "2020-10-11"
      version: v13
    secret:
      name: logging-loki-s3
      type: s3
    tls:
      caName: openshift-service-ca.crt # only for ODF
  storageClassName: DEFAULT_STORAGE_CLASS
  tenants:
    mode: openshift-logging
# ---
# apiVersion: logging.openshift.io/v1
# kind: ClusterLogging
# metadata:
#   name: instance
#   namespace: openshift-logging
# spec:
#   managementState: Managed
#   logStore:
#     type: lokistack
#     lokistack:
#       name: logging-loki
#   collection:
#     type: vector
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: collector
  namespace: openshift-logging
spec:
  serviceAccount:
    name: collector
  outputs:
  - name: default-lokistack
    type: lokiStack
    lokiStack:
      authentication:
        token:
          from: serviceAccount
      target:
        name: logging-loki
        namespace: openshift-logging
      tls:
        ca:
          key: service-ca.crt
          configMapName: openshift-service-ca.crt
  pipelines:
  - name: default-logstore
    inputRefs:
    - application # This specifies that application logs will be collected [42, 44, 48]
    - infrastructure # Optionally include infrastructure logs [42, 44]
    - audit # Optionally include audit logs, if permissions are granted [26, 29, 31, 41]
    outputRefs:
    - default-lokistack