graph LR;
    subgraph openshift-ingress;
    router;
    end;
    subgraph control-plane;
    istio-ingress;
    end;
    subgraph data-plane;
    istio-ingress-->frontend;
    frontend-->backend;
    end;
    subgraph external_system;
    httpbin-org;
    end;
