apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ubi8-openjdk-11-runtime
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://gitlab.com/ocp-demo/backend_quarkus'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: '11'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: backend
        image: nexus-registry-ci-cd.apps.cluster-zfzkr.zfzkr.sandbox1075.opentlc.com/backend:ubi8-openjdk-11-runtime
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.05"
            memory: 50Mi
          limits:
            cpu: "0.2"
            memory: 120Mi
        env:
          - name: APP_BACKEND
            value: https://httpbin.org/delay/5
          - name: APP_VERSION
            value: v1
          - name: quarkus.log.console.color
            value: 'false'
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          drop: ALL
          readOnlyRootFilesystem: false
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60
      terminationGracePeriodSeconds: 10

