apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm-hub
      endpoint: https://minio-minio-tenant-1.apps.cluster-qxgtt.qxgtt.example.opentlc.com
      insecure: true
      access_key: minio
      secret_key: minio123
