apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://gitlab.com/ocp-demo/backend_quarkus'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: '11'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: backend
        image: quay.io/voravitl/backend:native
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0.01"
            memory: 30Mi
          limits:
            cpu: "0.01"
            memory: 30Mi
        env:
          - name: APP_BACKEND
            value: https://httpbin.org/status/200
          - name: APP_VERSION
            value: v1
          - name: quarkus.log.console.color
            value: 'false'
        ports:
        - containerPort: 8080
      # initContainers:
      # - name: init-myservice
      #   image: busybox:1.28
      #   command: ['sh', '-c', "sleep 360"]
