apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-app-prod
  namespace: demo
  labels:
    environment: prod
    app: demo-app
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: manifests/apps-kustomize/overlays/prod
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: demo/demo-app-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: environment-prod
