apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: cluster1
spec:
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: ScanIfMissing
    listenOnCreates: true
    timeoutSeconds: 3
    listenOnEvents: true
    nodeSelector:
      node-role.kubernetes.io/acs: ""
    tolerations:
    - key: infra-acs
      value: reserved
      effect: NoSchedule
  sensor:
    nodeSelector:
      node-role.kubernetes.io/acs: ""
    tolerations:
    - key: infra-acs
      value: reserved
      effect: NoSchedule
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
  clusterName: cluster1
  centralEndpoint: 'central.stackrox.svc:443' # Central is created in namespace stackrox