apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-discovery
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - pods
      - services
      - namespaces
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch