---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend
  namespace: project1
spec:
  # advanced:
  #   restoreToOriginalReplicaCount: true
  fallback:
    replicas: 1
    failureThreshold: 3
  scaleTargetRef:
    name: backend-v1
    kind: Deployment
    apiVersion: apps/v1
  maxReplicaCount: 8
  minReplicaCount: 1
  pollingInterval: 30
  cooldownPeriod: 300 
  triggers:
    - authenticationRef:
        kind: TriggerAuthentication
        name: keda-trigger-auth-prometheus
      metadata:
        metricName: http_server_requests_seconds_count
        namespace: project1
        query: rate(http_server_requests_seconds_count{method="GET",uri="root",outcome="SUCCESS"}[1m])
        serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
        threshold: "15"
        authModes: "bearer"
      type: prometheus