apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-cpu
  namespace: project1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-v1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
  behavior:
    scaleDown: 
      policies: 
      - type: Pods 
        value: 1
        periodSeconds: 60 
      selectPolicy: Min 
      stabilizationWindowSeconds: 70 
    scaleUp: 
      policies:
      - type: Pods
        value: 5
        periodSeconds: 70
      selectPolicy: Max
      stabilizationWindowSeconds: 0