apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: backend-monitor
  name: backend-monitor
spec:
  endpoints:
  - interval: 30s
    port: 8080-tcp
    path: /q/metrics
    scheme: http
  - interval: 30s
    port: 8080-tcp
    path: /q/metrics/application
    scheme: http
  selector:
    matchLabels:
      app: backend
