apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://gitlab.com/ocp-demo/backend_quarkus'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: sa-discovery
      automountServiceAccountToken: false
      containers:
      - name: backend
        image: quay.io/voravitl/backend:native
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0.05"
            memory: 60Mi
          limits:
            cpu: "0.1"
            memory: 120Mi
        env:
          - name: APP_BACKEND
            value: http://localhost:8080/version
          - name: APP_VERSION
            value: v1
          - name: quarkus.log.console.color
            value: 'false'
        ports:
        - containerPort: 8080
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60