{
 "title": "Backend App",
 "description": "Backend Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\",uri=\"root\"}[60s])/60"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_example_quarkus_BackendResource_timeBackend_seconds_max)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_committed_bytes)/1048576"
    }
   ]
  }
 ]
}