apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://gitlab.com/ocp-demo/backend_quarkus'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: '2.16.1.Final'
spec:
  replicas: 14
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: rack 
        whenUnsatisfiable: DoNotSchedule 
        labelSelector: 
          matchLabels:
           app: backend
           version: v1
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname 
        whenUnsatisfiable: DoNotSchedule 
        labelSelector: 
          matchLabels:
           app: backend
           version: v1
      containers:
      - name: backend
        image: quay.io/voravitl/backend:native
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.05"
            memory: 50Mi
          limits:
            cpu: "0.2"
            memory: 120Mi
        env:
          - name: APP_BACKEND
            value: https://httpbin.org/delay/4
          - name: APP_VERSION
            value: v1
          - name: quarkus.log.console.color
            value: 'false'
        ports:
        - containerPort: 8080
        securityContext:
          seccompProfile: #"RuntimeDefault" or "Localhost"
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60

