apiVersion: compliance.openshift.io/v1alpha1
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    name: ocp4-cis-node
    kind: Profile
  - apiGroup: compliance.openshift.io/v1alpha1
    name: ocp4-cis
    kind: Profile 
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  name: default
  #name: default-auto-apply # For auto apply remidiation
  kind: ScanSetting
kind: ScanSettingBinding
metadata:
  name: cis-profile
  namespace: openshift-compliance
