apiVersion: "v1"
kind: Pod
metadata:
  name: cis-report
  namespace: openshift-compliance
  labels:
    app: report-generator
    app.kubernetes.io/component: reports
    app.kubernetes.io/instance: cis-report
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/part-of: reports
    app.openshift.io/runtime: redhat
spec:
  containers:
    - name: cis-report
      image: quay.io/voravitl/oscap:latest
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: /reports
        name: reports
      resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "0.5"
            memory: 600Mi
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: ocp4-cis
---
apiVersion: "v1"
kind: Pod
metadata:
  name: cis-worker-report
  namespace: openshift-compliance
  labels:
    app: report-generator
    app.kubernetes.io/component: reports
    app.kubernetes.io/instance: cis-worker-report
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/part-of: reports
    app.openshift.io/runtime: redhat
spec:
  containers:
    - name: cis-report
      image: quay.io/voravitl/oscap:latest
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: /reports
        name: reports
      resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "0.5"
            memory: 600Mi
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: ocp4-cis-node-worker
---
apiVersion: "v1"
kind: Pod
metadata:
  name: cis-master-report
  namespace: openshift-compliance
  labels:
    app: report-generator
    app.kubernetes.io/component: reports
    app.kubernetes.io/instance: cis-master-report
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/part-of: reports
    app.openshift.io/runtime: redhat
spec:
  containers:
    - name: cis-report
      image: quay.io/voravitl/oscap:latest
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: /reports
        name: reports
      resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "0.5"
            memory: 600Mi
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: ocp4-cis-node-master