apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-nodes
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
