apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-v1-memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-v1
  minReplicas: 1
  maxReplicas: 3
  targetMemoryUtilizationPercentage: 80