{
 "title": "Service Availability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "% Success of Backend Service",
   "type": "graph",
   "description": "% Success Response of Backend Service for last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=\"backend\",response_code!~\"5.*\"}[5m])) / sum(increase(istio_requests_total{destination_service_name=\"backend\"}[5m])) *100",
     "legendFormat": "% Service Availability"
    }
   ]
  },
  {
   "title": "Frontend Service Response Time",
   "type": "graph",
   "description": "99th Percentile Response time of Frontend Servcie",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"frontend\",response_code!~\"5*\"}[5m])) by (le))/1000"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service_name=\"backend\",response_code!~\"5.*\"}[5m])) / sum(increase(istio_requests_total{destination_service_name=\"backend\"}[5m])) *100"
    }
   ]
  },
  {
   "title": "Backend Service Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name=\"backend\",response_code!~\"5*\"}[5m])) by (le))/1000"
    }
   ]
  }
 ]
}