apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: demo
  labels:
    app: sso
  namespace: sso
spec:
  storageClassName: gp2
  multiAvailablityZones:
    enabled: false
  externalAccess:
    enabled: true
    tlsTermination: reencrypt
  podDisruptionBudget:
    enabled: true
  instances: 2
