apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leak-memory
  namespace: project1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leak
  minReplicas: 1
  maxReplicas: 3
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageValue: 100Mi
  behavior:
    scaleDown: 
      policies: 
      - type: Pods 
        value: 1
        periodSeconds: 60 
      selectPolicy: Min 
      stabilizationWindowSeconds: 70 
    scaleUp: 
      policies:
      - type: Pods
        value: 3
        periodSeconds: 70
      selectPolicy: Max
      stabilizationWindowSeconds: 0