apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: ACCESS_KEY_ID
  access_key_secret: SECRET_ACCESS_KEY
  bucketnames: S3_BUCKET
  endpoint: ENDPOINT
  region: REGION
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  rules:
    enabled: true # Enable Alert
    selector:
      matchLabels:
        openshift.io/cluster-monitoring: "true" # Only consider rules matching these labels
    namespaceSelector:
      matchLabels:
        openshift.io/cluster-monitoring: "true" # Only consider rules in namespaces matching these labels
  size: 1x.extra-small #1x.small
  storage:
    schemas:
    # - version: v12
    #   effectiveDate: "2022-06-01"
    - version: v11
      effectiveDate: "2020-10-11"    
    secret:
      name: logging-loki-s3
      type: s3
    tls:
      caName: openshift-service-ca.crt # only for ODF
  storageClassName: DEFAULT_STORAGE_CLASS
  tenants:
    mode: openshift-logging
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
  collection:
    type: vector