apiVersion: loki.grafana.com/v1
kind: AlertingRule
metadata:
  name: backend
  namespace: api
  labels: 
    openshift.io/cluster-monitoring: 'true'
spec:
  tenantID: "application"
  groups:
    - name: BackendService
      limit: 5
      interval: 1m
      rules:
        - alert: BackendServiceError
          expr: |
            count_over_time({log_type="application", kubernetes_namespace_name="api"} |~ "Return Code: 5.*" |level=~"error|err|eror" [1m]) > 0
          for: 10s
          labels:
            severity: critical 
          annotations:
            summary:  "{{ $labels.pod }} get error response with: {{ $value }}"
            description: "{{ $labels.pod }} get error response with: {{ $value }}"