apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki
  namespace: openshift-storage
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: loki
  generateBucketName: loki
  objectBucketName: obc-openshift-storage-loki
  storageClassName: openshift-storage.noobaa.io