apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: acs
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,infra]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/acs: ""
  paused: false
