apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: netobserv
  namespace: openshift-storage
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: netobserv
  generateBucketName: netobserv
  objectBucketName: obc-openshift-storage-netobserv
  storageClassName: openshift-storage.noobaa.io