apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-httpbin
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector: {}
          namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
