apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-group-ingress
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress