apiVersion: apps/v1
kind: Deployment
metadata:
  name: openssl
  labels:
    app.kubernetes.io/component: network-tools
    app.kubernetes.io/instance: network-tools
    app.kubernetes.io/part-of: Tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openssl
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openssl
    spec:
      containers:
      - name: openssl
        image: registry.access.redhat.com/ubi8/openssl
        command: ["sleep", "6000"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.1"
            memory: 250Mi
          limits:
            cpu: "0.2"
            memory: 700Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          drop: ALL
          readOnlyRootFilesystem: false
      terminationGracePeriodSeconds: 10

