apiVersion: compliance.openshift.io/v1alpha1
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    name: ocp4-pci-dss
    kind: Profile
  - apiGroup: compliance.openshift.io/v1alpha1
    name: ocp4-pci-dss-node
    kind: Profile 
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  name: default
  #name: default-auto-apply
  kind: ScanSetting
kind: ScanSettingBinding
metadata:
  name: pci-dss-profile
  namespace: openshift-compliance
