apiVersion: "v1"
kind: Pod
metadata:
  name: pci-dss-report
  namespace: openshift-compliance
  labels:
    app: report-generator
    app.kubernetes.io/component: reports
    app.kubernetes.io/instance: pci-dss-report
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/part-of: reports
    app.openshift.io/runtime: redhat
spec:
  containers:
    - name: pci-dss-report
      image: quay.io/voravitl/oscap:latest
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: /reports
        name: reports
      resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "0.5"
            memory: 600Mi
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: ocp4-pci-dss
---
apiVersion: "v1"
kind: Pod
metadata:
  name: pci-dss-worker-report
  namespace: openshift-compliance
  labels:
    app: report-generator
    app.kubernetes.io/component: reports
    app.kubernetes.io/instance: pci-dss-worker-report
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/part-of: reports
    app.openshift.io/runtime: redhat
spec:
  containers:
    - name: pci-dss-report
      image: quay.io/voravitl/oscap:latest
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: /reports
        name: reports
      resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "0.5"
            memory: 600Mi
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: ocp4-pci-dss-node-worker
---
apiVersion: "v1"
kind: Pod
metadata:
  name: pci-dss-master-report
  namespace: openshift-compliance
  labels:
    app: report-generator
    app.kubernetes.io/component: reports
    app.kubernetes.io/instance: pci-dss-master-report
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/part-of: reports
    app.openshift.io/runtime: redhat
spec:
  containers:
    - name: pci-dss-report
      image: quay.io/voravitl/oscap:latest
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: /reports
        name: reports
      resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "0.5"
            memory: 600Mi
  volumes:
    - name: reports
      persistentVolumeClaim:
        claimName: ocp4-pci-dss-node-master
