apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: prod
    namespace: openshift-ingress-operator
  spec:
    domain: SHARD_DOMAIN
    replicas: 2
    endpointPublishingStrategy:
      type: HostNetwork
      hostNetwork:
        httpPort: 81
        httpsPort: 9444
        statsPort: 1940
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
    routeSelector:
      matchLabels:
        type: prod
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""