apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    type: prod 
  name: frontend
spec:
  host: frontend.prod.apps.cluster-6w6fn.6w6fn.sandbox1666.opentlc.com
  port:
    targetPort: http
  #subdomain: frontend
  # tls:
  #   termination: edge
  to:
    kind: Service
    name: frontend