apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  labels:
    app.kubernetes.io/component: rsyslog
    app.kubernetes.io/instance: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: rsyslog
        image: registry.redhat.io/rhel8/rsyslog
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.05"
            memory: 50Mi
          limits:
            cpu: "0.2"
            memory: 300Mi
        # env:
        #   - name: APP_BACKEND
        #     value: https://httpbin.org/status/200
        #   - name: APP_VERSION
        #     value: v1
        #   - name: quarkus.log.console.color
        #     value: 'false'
        #   - name: quarkus.rest-client.read-timeout
        #     value: "30000"
        ports:
        - containerPort: 514
        securityContext:
          seccompProfile: #"RuntimeDefault" or "Localhost"
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  labels:
    app: rsyslog
spec:
  ports:
  - port: 514
    targetPort: 514
  selector:
    app: rsyslog
