apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-todo
  namespace: todo
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment 
    name:       todo 
  updatePolicy:
    updateMode: "Auto" # updateMode: Off, Auto, Initial and Recreate
    # autoPolicy:
    #   policy: "Conservative"
  resourcePolicy:
    containerPolicies:
    - containerName: "todo"
      minAllowed:
        cpu: "100m"
        memory: "100Mi"
      maxAllowed:
        cpu: "500m"
        memory: "600Mi"
    - containerName: "istio-proxy"
      mode: "Off"