---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: federated-monitor
  name: federated-prometheus
  namespace: thanos
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: web
    relabelings:
    - replacement: cluster1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: ocp_cluster
    path: /federate
    honorLabels: true
    params:
      'match[]': 
        - '{namespace="reverse-words-app"}'
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: prometheus-k8s.openshift-monitoring.svc.cluster.local
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      prometheus: "k8s"