---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: federated-monitor
  name: reverse-words
  namespace: thanos
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: http
    relabelings:
    - replacement: cluster1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: ocp_cluster
    path: /metrics
    params:
      'match[]': 
        - '{__name__=~".+"}'
    scheme: http
  namespaceSelector:
    matchNames:
    - reverse-words-app
  selector:
    matchLabels:
      app: "reverse-words"