apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: APP_BACKEND
              value: https://httpbin.org/status/200