apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo
        image: quay.io/voravitl/todo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "0.1"
            memory: 200Mi
          limits:
            cpu: "0.2"
            memory: 300Mi