apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo
  namespace: todo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60