apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
    # name: default/api-cluster-a42c-a42c-sandbox52-opentlc-com:6443/opentlc-mgr
    # argocd cluster add default/api-cluster-a42c-a42c-sandbox52-opentlc-com:6443/opentlc-mgr --name=
  project: default
  source:
    directory:
      recurse: false
    path: manifests/apps-kustomize/overlays/dev
    repoURL: https://github.com/rhthsa/openshift-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
