{
 "title": "Backend App",
 "description": "Backend Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_concurrentBackend_current"
    }
   ]
  },
  {
   "title": "Total Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_countBackend_total"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    { "expr": "base_memory_usedHeap_bytes" }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "application_com_example_quarkus_BackendResource_timeBackend_max_seconds"
    }
   ]
  }
 ]
}