apiVersion: v1
kind: Route
metadata:
  name: canary
spec:
  to:
    kind: Service
    name: front-main
    weight: 100
  alternateBackends:
  - kind: Service
    name: front-sub 
    weight: 0
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
